import 'dart:async';
import 'dart:convert';
import 'dart:typed_data';

import 'package:web_socket_channel/io.dart';
import 'package:web_socket_channel/web_socket_channel.dart';

/// High-level state of the Jarvis voice core. The UI (orb + terminal)
/// subscribes to this to react to listening / processing / speaking.
enum JarvisCoreState { idle, connecting, listening, processing, speaking }

/// Real-time bidirectional voice client for the Gemini Live API.
///
/// Protocol (v1alpha BidiGenerateContent over WebSocket):
///  1. On connect -> immediately send the `setup` message (model + persona).
///  2. Stream mic audio as Base64 PCM chunks via `realtimeInput.mediaChunks`.
///  3. Receive model audio from `serverContent.modelTurn.parts[].inlineData`.
class GeminiLiveService {
  GeminiLiveService._();
  static final GeminiLiveService instance = GeminiLiveService._();

  /// Live API endpoint (BidiGenerateContent).
  static const String wsUrl =
      'wss://generativelanguage.googleapis.com/ws/google.ai.generativelanguage.v1alpha.GenerativeService.BidiGenerateContent?key=AQ.Ab8RN6JM_bMfjCv61D1lnB7IIbPdBwOhqNCjXiImQHr5d63_xQ';

  /// Setup frame sent the exact moment the socket opens — BEFORE any audio.
  /// Persona: loyal futuristic assistant addressing "Sejan ( Supreme)" in Bengali.
  static const String setupMessage =
      '{"setup": {"model": "models/gemini-2.0-flash-exp", '
      '"systemInstruction": {"parts": [{"text": "You are Jarvis, a highly '
      'advanced AI assistant. You must address the user as '
      "'Sejan ( Supreme)'. "
      'Speak entirely in natural Bengali in a loyal, friendly, and futuristic '
      'tone."}]}}}';

  WebSocketChannel? _channel;
  StreamSubscription<dynamic>? _messageSub;

  final StreamController<Uint8List> _audioOutController =
      StreamController<Uint8List>.broadcast();
  final StreamController<String> _modelTextController =
      StreamController<String>.broadcast();
  final StreamController<String> _inputTextController =
      StreamController<String>.broadcast();
  final StreamController<JarvisCoreState> _stateController =
      StreamController<JarvisCoreState>.broadcast();

  /// Decoded PCM bytes of Jarvis's voice replies.
  Stream<Uint8List> get audioOutput => _audioOutController.stream;

  /// Text spoken/generated by the model (for terminal subtitles).
  Stream<String> get modelText => _modelTextController.stream;

  /// Transcription of what the user said (used by the command router).
  Stream<String> get inputText => _inputTextController.stream;

  /// Core state changes for UI reaction.
  Stream<JarvisCoreState> get state => _stateController.stream;

  bool get isConnected => _channel != null;

  // ---------------------------------------------------------------------------
  // CONNECTION
  // ---------------------------------------------------------------------------

  Future<void> connect() async {
    if (_channel != null) return; // already connected

    _stateController.add(JarvisCoreState.connecting);

    final channel = IOWebSocketChannel.connect(
      Uri.parse(wsUrl),
      pingInterval: const Duration(seconds: 15),
    );
    _channel = channel;

    // REQUIRED: send setup before streaming any audio.
    channel.sink.add(setupMessage);

    _messageSub = channel.stream.listen(
      _onServerData,
      onError: (Object error) {
        _stateController.add(JarvisCoreState.idle);
        disconnect();
      },
      onDone: () {
        _stateController.add(JarvisCoreState.idle);
        disconnect();
      },
      cancelOnError: false,
    );

    _stateController.add(JarvisCoreState.listening);
  }

  Future<void> disconnect() async {
    await _messageSub?.cancel();
    _messageSub = null;
    try {
      await _channel?.sink.close();
    } catch (_) {}
    _channel = null;
    _stateController.add(JarvisCoreState.idle);
  }

  // ---------------------------------------------------------------------------
  // INPUT: Mic -> Server
  // ---------------------------------------------------------------------------

  /// Sends one chunk of raw 16 kHz mono 16-bit PCM to Gemini as Base64.
  void sendAudioChunk(Uint8List pcmBytes) {
    final channel = _channel;
    if (channel == null || pcmBytes.isEmpty) return;

    final payload = jsonEncode(<String, dynamic>{
      'realtimeInput': <String, dynamic>{
        'mediaChunks': <Map<String, dynamic>>[
          <String, dynamic>{
            'mimeType': 'audio/pcm;rate=16000',
            'data': base64Encode(pcmBytes),
          },
        ],
      },
    });

    try {
      channel.sink.add(payload);
    } catch (_) {
      // Socket died mid-stream; onDone/onError will clean up.
    }
  }

  // ---------------------------------------------------------------------------
  // OUTPUT: Server -> App
  // ---------------------------------------------------------------------------

  void _onServerData(dynamic data) {
    try {
      final Map<String, dynamic> message = jsonDecode(data.toString());

      final serverContent = message['serverContent'];
      if (serverContent is Map) {
        // --- Model turn: audio and/or text parts ---
        final modelTurn = serverContent['modelTurn'];
        if (modelTurn is Map) {
          final parts = modelTurn['parts'];
          if (parts is List && parts.isNotEmpty) {
            final part = parts.first;
            if (part is Map) {
              final inlineData = part['inlineData'];
              if (inlineData is Map && inlineData['data'] != null) {
                final pcmBytes =
                    base64Decode(inlineData['data'].toString());
                if (pcmBytes.isNotEmpty) {
                  _stateController.add(JarvisCoreState.speaking);
                  _audioOutController.add(Uint8List.fromList(pcmBytes));
                }
              }
              final text = part['text'];
              if (text is String && text.trim().isNotEmpty) {
                _modelTextController.add(text);
              }
            }
          }
        }

        // --- Input transcription (if the server provides it) ---
        final inputTranscription = serverContent['inputTranscription'];
        if (inputTranscription is Map &&
            inputTranscription['text'] is String) {
          final text = inputTranscription['text'] as String;
          if (text.trim().isNotEmpty) {
            _stateController.add(JarvisCoreState.processing);
            _inputTextController.add(text);
          }
        }

        // --- Output transcription (fallback subtitle source) ---
        final outputTranscription = serverContent['outputTranscription'];
        if (outputTranscription is Map &&
            outputTranscription['text'] is String) {
          final text = outputTranscription['text'] as String;
          if (text.trim().isNotEmpty) {
            _modelTextController.add(text);
          }
        }

        // --- Turn finished ---
        if (serverContent['turnComplete'] == true) {
          _stateController.add(JarvisCoreState.listening);
        }
      }
    } catch (_) {
      // Malformed frame; ignore and keep the session alive.
    }
  }
}